import React from 'react';
import { AspectRatio } from '../types';
import { PhotoIcon } from './Icons';

interface ImageDisplayProps {
  imageUrl: string | null;
  loading: boolean;
  error: string | null;
  aspectRatio: AspectRatio;
}

const aspectRatioClasses: Record<AspectRatio, string> = {
  '1:1': 'aspect-square',
  '3:4': 'aspect-[3/4]',
  '4:3': 'aspect-[4/3]',
  '9:16': 'aspect-[9/16]',
  '16:9': 'aspect-[16/9]',
};

const SkeletonLoader: React.FC<{ aspectRatio: AspectRatio }> = ({ aspectRatio }) => (
    <div className={`w-full max-w-2xl mx-auto bg-gray-800 rounded-lg overflow-hidden ${aspectRatioClasses[aspectRatio]}`}>
        <div className="w-full h-full bg-gray-700 animate-pulse"></div>
    </div>
);

const Placeholder: React.FC = () => (
    <div className="w-full max-w-2xl mx-auto aspect-square flex flex-col items-center justify-center bg-gray-800/50 border-2 border-dashed border-gray-700 rounded-lg text-gray-500">
        <PhotoIcon className="w-16 h-16 mb-4" />
        <p className="text-lg font-medium">Your generated image will appear here</p>
        <p className="text-sm">Enter a prompt and click "Generate"</p>
    </div>
);

const ErrorDisplay: React.FC<{ message: string }> = ({ message }) => (
  <div className="w-full max-w-2xl mx-auto p-4 bg-red-900/50 border border-red-500 rounded-lg text-red-300">
    <h3 className="font-bold mb-2">An Error Occurred</h3>
    <p className="text-sm">{message}</p>
  </div>
);

export const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl, loading, error, aspectRatio }) => {
  return (
    <div className="w-full mt-4">
      {loading && <SkeletonLoader aspectRatio={aspectRatio} />}
      {error && !loading && <ErrorDisplay message={error} />}
      {!loading && !error && imageUrl && (
        <div className={`w-full max-w-2xl mx-auto rounded-lg overflow-hidden shadow-2xl shadow-purple-900/20 border border-purple-500/30`}>
             <img src={imageUrl} alt="Generated by AI" className={`w-full h-full object-cover ${aspectRatioClasses[aspectRatio]}`} />
        </div>
      )}
      {!loading && !error && !imageUrl && <Placeholder />}
    </div>
  );
};